version: '3.8'

services: 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234=
      - TCP_CONNECTION_ENCRYPTION=Optional
    ports:
      - "50000:1433"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 60 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -C -U sa -P Test1234= -i /docker-entrypoint-initdb.d/init.sql &&
      echo 'Database initialized successfully' || echo 'Database initialization failed';
      tail -f /dev/null
      "
      
    networks:
      - mydbnetwork
  
  webapi:
    build: ./APIDemoDocker
    ports: 
      - "50001:8080"
    networks:
      - mydbnetwork
    depends_on:
      - sqlserver
    restart: always

networks:
  mydbnetwork:
    driver: bridge
  
